/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import controller.CategoriaController;
import javax.swing.JOptionPane;
import model.Categoria;
import org.apache.commons.lang3.StringUtils;

/**
 *
 * @author jodarove
 */
public class CategoriaForm extends javax.swing.JDialog {
    private Categoria categoria = new Categoria();
    /**
     * Creates new form CategoriaForm
     */
    public CategoriaForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        btnOk.setText("Agregar");
    }
    
    //Pasamos Categoria como ultimo parametro.
    public CategoriaForm(java.awt.Frame parent, boolean modal, Categoria categoria) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        btnOk.setText("Guardar");
        //seteamos la caja de texto
        txtNombre.setText(categoria.getNombre());
        //asignamos la categoria que recibimos del tblCategoria
        this.categoria = categoria;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Agregar Categoría");
        getContentPane().add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setMinimumSize(new java.awt.Dimension(469, 83));
        jPanel1.setPreferredSize(new java.awt.Dimension(469, 83));
        jPanel1.setLayout(new java.awt.GridLayout(2, 2));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nombre:");
        jPanel1.add(jLabel1);

        txtNombre.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtNombre.setToolTipText("Nombre");
        txtNombre.setMinimumSize(new java.awt.Dimension(100, 20));
        txtNombre.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel1.add(txtNombre);

        btnOk.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnOk.setText("Agregar");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        jPanel1.add(btnOk);

        btnCancelar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // si validar datos devuelve true seteamos los datos
        if (validarDatos()) {
            setDatos();
            //tomamos el texto del boton y si es agregar ejecutamos agregar else editar
            if (btnOk.getText().equals("Agregar")) {
                agregar();
            }else{
                editar();
            }
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cancelar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private boolean validarDatos(){
        String nombre = txtNombre.getText();
        // chequeamos si nombre es null o vacio
        if (nombre == null || nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor complete los campos", "Campos incompletos", JOptionPane.INFORMATION_MESSAGE);
            txtNombre.requestFocus();
            return false;
        } else {
            return true;
        }
    }
    private void setDatos(){
        categoria.setNombre(StringUtils.capitalize(txtNombre.getText()));
    }
    
    private void agregar(){
        try {
            CategoriaController.add(categoria);
            JOptionPane.showMessageDialog(rootPane, "Categoría agregada!", "Información", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } catch (Exception e) {
            System.err.println("Error en agregar categoría " + e);
        }
    }
    
    private void editar(){
        try {
            CategoriaController.update(categoria);
            JOptionPane.showMessageDialog(rootPane, "Categoría actualizada!", "Información", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } catch (Exception e) {
            System.err.println("Error en editar categoría " + e);
        }
    }
    
    private void cancelar(){
        dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CategoriaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CategoriaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CategoriaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CategoriaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CategoriaForm dialog = new CategoriaForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
