/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import controller.CiudadController;
import javax.swing.JOptionPane;
import model.Ciudad;
import org.apache.commons.lang3.StringUtils;

/**
 *
 * @author jodarove
 */
public class CiudadForm extends javax.swing.JDialog {
    private Ciudad ciudad = new Ciudad();
    /**
     * Creates new form CiudadForm
     */
    public CiudadForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        // centra el form
        setLocationRelativeTo(null);
        lblTitulo.setText("Agregar Ciudad");
        btnOk.setText("Agregar");
    }
    
    public CiudadForm(java.awt.Frame parent, boolean modal, Ciudad ciudad) {
        super(parent, modal);
        initComponents();
        // centra el form
        setLocationRelativeTo(null);
        this.ciudad = ciudad;
        lblTitulo.setText("Editar Ciudad");
        btnOk.setText("Guardar");
        txtNombre.setText(ciudad.getNombre());
    }    

    private boolean validarDatos(){
        String nombre = txtNombre.getText();
        if (nombre == null || nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor complete los campos.", "Campos incompletos",  JOptionPane.INFORMATION_MESSAGE);
            txtNombre.requestFocus();
            return false;
        } else {
            return true;
        }
    }
    
    private void setDatos(){
        ciudad.setNombre(StringUtils.capitalize(txtNombre.getText()));
    }
    
    private void agregar(){
        try {
            CiudadController.add(ciudad);
            JOptionPane.showMessageDialog(rootPane, "Ciudad agregada!", "Información", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } catch (Exception e) {
            System.err.println("Error al agregar Ciudad: " + e);
        }
    }
    
    private void editar(){
        try {
            CiudadController.update(ciudad);
            JOptionPane.showMessageDialog(rootPane, "Ciudad Actualizada!", "Información", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } catch (Exception e) {
            System.err.println("Error al editar Ciudad: " + e);
        }
    }
    
    private void cancelar(){
        dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbDepartamentos = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(469, 112));

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("jLabel1");
        getContentPane().add(lblTitulo, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(3, 2));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Departamento:");
        jPanel1.add(jLabel1);

        cmbDepartamentos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cmbDepartamentos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbDepartamentos);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2);

        txtNombre.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(txtNombre);

        btnOk.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnOk.setText("jButton1");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        jPanel1.add(btnOk);

        btnCancelar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        if (validarDatos()) {
            setDatos();
            if (btnOk.getText().equals("Agregar")) {
                agregar();
            } else {
                editar();
            }
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cancelar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CiudadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CiudadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CiudadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CiudadForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CiudadForm dialog = new CiudadForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox cmbDepartamentos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
