/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import javax.swing.JOptionPane;


/**
 *
 * @author jodarove
 */
public class MenuPrincipal extends javax.swing.JFrame {
    private static final String CLICK_CAJA_V2 = " | ClickCaja V 2.0";
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        setLocationRelativeTo(null); //centrar la ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOpenTesting = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuItemSalir = new javax.swing.JMenuItem();
        menuConfiguracion = new javax.swing.JMenu();
        menuItemCategoria = new javax.swing.JMenuItem();
        menuItemDepartamento = new javax.swing.JMenuItem();
        menuItemCiudad = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ClickCaja V2");

        btnOpenTesting.setText("Run testing");
        btnOpenTesting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenTestingActionPerformed(evt);
            }
        });

        menuArchivo.setText("Archivo");
        menuArchivo.setToolTipText("Archivo");
        menuArchivo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        menuItemSalir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        menuItemSalir.setText("Salir");
        menuItemSalir.setToolTipText("Salir");
        menuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(menuItemSalir);

        jMenuBar1.add(menuArchivo);

        menuConfiguracion.setText("Configuración");
        menuConfiguracion.setToolTipText("Configuración");
        menuConfiguracion.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        menuItemCategoria.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        menuItemCategoria.setText("Categoría");
        menuItemCategoria.setToolTipText("Categoría");
        menuItemCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCategoriaActionPerformed(evt);
            }
        });
        menuConfiguracion.add(menuItemCategoria);

        menuItemDepartamento.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        menuItemDepartamento.setText("Departamento");
        menuItemDepartamento.setToolTipText("Crear, Buscar, Editar, Eliminar Departamentos");
        menuItemDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDepartamentoActionPerformed(evt);
            }
        });
        menuConfiguracion.add(menuItemDepartamento);

        menuItemCiudad.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        menuItemCiudad.setText("Ciudad");
        menuItemCiudad.setToolTipText("Abre Control Ciudades");
        menuItemCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCiudadActionPerformed(evt);
            }
        });
        menuConfiguracion.add(menuItemCiudad);

        jMenuBar1.add(menuConfiguracion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnOpenTesting)
                .addContainerGap(321, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(220, Short.MAX_VALUE)
                .addComponent(btnOpenTesting)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenTestingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenTestingActionPerformed
        System.out.println(JOptionPane.showConfirmDialog(this, "you want this?"));
        FormTesting ventana = new FormTesting();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnOpenTestingActionPerformed

    private void menuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItemSalirActionPerformed

    private void menuItemCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCategoriaActionPerformed
        CategoriaControlForm abrir = new CategoriaControlForm(this, true);
        abrir.setTitle("Control Categorias" + CLICK_CAJA_V2);
        abrir.setVisible(true);
    }//GEN-LAST:event_menuItemCategoriaActionPerformed

    private void menuItemDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDepartamentoActionPerformed
        if (evt.ACTION_PERFORMED == 1001) {
            DepartamentoControlForm abrir = new DepartamentoControlForm(this, true);
            abrir.setTitle("Control Departamentos" + CLICK_CAJA_V2);
            abrir.setVisible(true);
        }
    }//GEN-LAST:event_menuItemDepartamentoActionPerformed

    private void menuItemCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCiudadActionPerformed
        if (evt.ACTION_PERFORMED == 1001) {
            CiudadControlForm abrir = new CiudadControlForm(this, true);
            abrir.setTitle("Control Ciudades" + CLICK_CAJA_V2);
            abrir.setVisible(true);
        }
    }//GEN-LAST:event_menuItemCiudadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpenTesting;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuConfiguracion;
    private javax.swing.JMenuItem menuItemCategoria;
    private javax.swing.JMenuItem menuItemCiudad;
    private javax.swing.JMenuItem menuItemDepartamento;
    private javax.swing.JMenuItem menuItemSalir;
    // End of variables declaration//GEN-END:variables
}
